### ISSUE TITLE
Error detected while processing function magit#show_magit: line  119: E714: List required

### ISSUE THREAD

**Issue by alok** [jreybert/vimagit#100]
This happens every time I run `:Magit`. I'm using the `next` branch.

```
Error detected while processing function magit#show_magit:
line  119:
E714: List required
```

**Comment by jreybert** [comment]
Did you redefine `g:magit_folding_toggle_mapping`. If so, it must a list, for example:
`let g:magit_folding_toggle_mapping = [ '<CR>' ]`

**Comment by alok** [comment]
Wow I had a bad moment of not RTFM. Thanks. Adding the mapping to a list fixed it.

**Comment by jreybert** [comment]
Mappings should move to `<Plug>(magit_*)` in a near future, stay tuned ;)
