### ISSUE TITLE
Mimic fugitive default mappings

### ISSUE THREAD

**Issue by jreybert** [jreybert/vimagit#101]
@justinmk input:

> fwiw, i think vimagit would gain a bit more traction if it used fugitive-like mappings where possible
> e.g., ca in fugitive is like CA in vimagit. but it's different for no reason
> better for users if the same mappings are used for analogous concepts
> and CC is cc in fugitive
> vimagit's N is analogous to <c-n> in fugitive

**Comment by jreybert** [comment]
@khalidchawtany @yevhen-m could you please give a try to branch `dev/mapping` and tell me if you like new mappings?

**Comment by alok** [comment]
I wouldn't change `CC` to `cc` since `cc` is pretty handy for writing the commit message, since it clears the line.

Also, mapping over `l`, `r`, `e`, `m`, and (maybe) `f` isn't a great idea since often I want to:

- move the cursor right (`l`)
- change a letter in a commit message (`r`)
- move by word (`e`)
- set marks (`m`)
- jump to a letter (usually in a commit message) (`f`)

If you could find a way to make those mappings only work outside the commit message region (maybe with a try/except block, though that's really hacky), I'm in favor. The other mappings are fine.

**Comment by yevhen-m** [comment]
Absolutely agree, @Alok. It's a bad idea to change native mappings to something else. I don't like that `M` & `L` are remapped for this reason as well.

**Comment by jreybert** [comment]
@justinmk remarks about actual mapping (which are almost all caps mappings) are close to fugitive mappings, but could be the same (which would ease the usage of vimagit for fugitive users). Also, use non caps mappings for usual action like staging frees a finger :)

There is a trade off to find. vimagit is a little bit more than a usual vim plugin, it is a git UI embedded in vim. Then, it needs to use a lot of "easy to type" single key mappings to perform git actions efficiently.

@Alok good point for the "out of commit section" idea. I will look how ugly it could be. Another solution would be to open a new window to write the commit message, but I like the idea to stay in the same window.

@yevhen-m  these mappings are applied in the vimagit buffer only. You seem to dislike caps mappings too with `L` and `M`. Did you remap these mappings? What would you suggest? As there is a lot of mapping to remember, they must be mnemonic.

**Comment by khalidchawtany** [comment]
It is 1:00 am. I would be more than happy to try them tomorrow  :)

**Comment by jreybert** [comment]
No no no, I want an anwser now! Get up!! 😄 

Have a nice night, and thanks for the upcoming review.

**Comment by khalidchawtany** [comment]
>No no no, I want an anwser now! Get up!! 

Ha ha. I was long gone to 😴

Although sometimes I use the previous mappings accidentally, I would definitely would like to have the new ones 👍 

@jreybert I am not able to stage visually selected lines `vs`, marked lines `ms`, or just a line `l`; unless there is a new line at the end of my file.
Maybe this is the same as before. However, I haven't noticed as I always have a blank line at the end of my files.

I get the following:

```
Error detected while processing function magit#stage_vselect[9]..<SNR>54_mg_create_diff_from_select:
line   42:
E605: Exception not caught: visual selection error: \ No newline at end of file
```

**Comment by jreybert** [comment]
Crap. Could you please try on branch next and check if there is the same behavior? Whatever the result, could you open an issue, precising the branch, your [n]vim version, your git version and a step by step way to reproduce this bug.

Thanks for your review!

**Comment by jreybert** [comment]
Actually, use small case `s` `f` `m` `r`... mappings is a bad idea, as it conflicts with very standard mappings.

The only change made in 488b619 is to map `<C-n>` `<C-p>` instead of `N` `P` to jump around the hunks
