### ISSUE TITLE
consider clearing and restoring user-defined mappings that conflict in magit buffer

### ISSUE THREAD

**Issue by alok** [jreybert/vimagit#106]
I have S mapped to start a macro, so `S` also staging a hunk is annoying as it pauses a bit to figure out which mapping was meant. There's only so many keys, so remapping can be a nuisance. vim doesn't seem to have a builtin way to unmap global mappings locally, so I was wondering if magit could save user mappings, unmap them, and then restore them after leaving the magit buffer.

**Comment by jreybert** [comment]
I plan to use `<Plug>` mappings. It will let the user much more flexibility (re)defining its mappings #102 

I should also add `<nowait>`, which should fix your pause issue #85

**Comment by jreybert** [comment]
@Alok could you please give a try to branch `dev/mapping`

I added `<nowait>` in default mappings, it should fix your problem
