### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by sedm0784** [jreybert/vimagit#108]
Windows: 8.1
Vim: 7.4
Git for Windows: 2.6.1.windows.1

I'm having trouble getting vimagit running on my Windows box.

Git is in my path (and running `:!git` in the command-line window opens a Windows command prompt in which the command `cmd.exe /c (git)` successfully prints out the git usage message, followed by `shell returned 1 Hit any key to close this window...`.

However, I get the behaviour described in issue #39. If I set up `g:magit_git_cmd` as described in issue #39, then I get the following behaviour on running `:Magit`:

1. The following message is printed:

       Error detected while processing function magit#show_magit..magit#update_buffer:
       line    3:
       Not in magit buffer but in magit:\\[path to my git repo]\
       Press ENTER or type command to continue

2. A vertical split is opened with an buffer with no contents and with path: `\magit:\\[path to my git repo]\`

**Comment by jreybert** [comment]
Hi,

could you try branch next please? Or at least cheery pick c4146ed

It should fix this problem, but I fear it hides other problems. It is quite difficult to me to test on windows platform...
