### ISSUE TITLE
Amend doesn't bring up old commit message.

### ISSUE THREAD

**Issue by alok** [jreybert/vimagit#109]
I type `CA`, both inside and outside of the commit box, and it fails to bring up the last commit message (which does exist). Is anyone else having this issue?

**Comment by jreybert** [comment]
@Alok `CA` works well on both branches `master` and `next`. Which version of vimagit are you using? What is your current SHA1?

**Comment by jreybert** [comment]
Right, I got it: `CA` must be called before you opened the commit box. It means that:
```
S
S
CA
CC
```
works, but:
```
S
S
CC
CA
CC
```
do not work.

Maybe vimagit should detect this pattern and return an error.

**Comment by alok** [comment]
It could also automatically toggle the commit type when it makes sense to do so.

**Comment by jreybert** [comment]
Hm, it would make sense indeed...

I am entirely satisfied by the actual Commit Amend behaviour, it should show the status of the amended commit. What do you think?

**Comment by alok** [comment]
It's not that big a deal to me, so do whatever pleases you.

**Comment by jreybert** [comment]
@Alok I realize that I forgot something in my last sentence.

My actual question was:
I am **NOT** entirely satisfied by the actual Commit Amend behavior, it should show the status of the amended commit. What do you think?
To be more clear, there are two kind of amend: amend only the commit message, and amend the commit content (e.g. unstage some file from previous commit).

Would you find this useful?

**Comment by jreybert** [comment]
BTW, I pushed your requested feature in branch `dev/issue_109`. Could you test it please?

**Comment by alok** [comment]
it works

**Comment by jreybert** [comment]
Merged in master and present in release 1.7.2

**Comment by vais** [comment]
Hi, @jreybert, did you ever get around to implementing the second kind of amend, i.e. the kind where you can amend commit *content?* (E.g. unstage files from the commit being amended, review changes, etc.) Because that *would* be very useful indeed!

> I am NOT entirely satisfied by the actual Commit Amend behavior, it should show the status of the amended commit. What do you think?
>
> To be more clear, there are two kind of amend: amend only the commit message, and amend the commit content (e.g. unstage some file from previous commit).
> 
> Would you find this useful?

If not, then, for what it's worth at this point in time, **yes** please :)

**Comment by jreybert** [comment]
Hi @vais could you open a new request for this feature? I did not have much time to spend on vimagit this last year, but I will try to find some during the christmas holidays.
If you mind, it could be great to share a step by step usage example, to make sure we have the same usage in mind.

**Comment by vais** [comment]
Sorry for the delay, @jreybert, here's the new issue: https://github.com/jreybert/vimagit/issues/181
