### ISSUE TITLE
Strange behaviour when open help message in commit mode amend

### ISSUE THREAD

**Issue by deathmaz** [jreybert/vimagit#110]
Hi @jreybert, i recorded the issue with `asciinema` - https://asciinema.org/a/9qq3wf1sz5pslilrt116sjm1t
So when i press `CA` you can see `Commit message` section with my previous commit in it. But when i pres `?` to see help and then press it again to close it you can see that `Commit message` section is messed up. And it get's messed up even more when i press `?` repeatedly.

I'm using `NVIM 0.1.7`.

Thank you for a nice plugin!

**Comment by jreybert** [comment]
Thanks for the report (and the screencast :) ).

Indeed, this is a bug.
