### ISSUE TITLE
Errors when opening `Magit`

### ISSUE THREAD

**Issue by jackfranklin** [jreybert/vimagit#112]
I've installed the plugin through vim plug, and I see a lot of errors when I immediately run `:Magit`:

<img width="890" alt="screen shot 2017-01-05 at 13 19 28" src="https://cloud.githubusercontent.com/assets/193238/21681977/d4c734fc-d349-11e6-9571-ed4afb838906.png">

I was using Neovim so I thought that might be the issue but it's not, regular Vim 7 has this problem too.

Any thoughts you have are much appreciated!

**Comment by jreybert** [comment]
Sorry for the late.

What is your vimagit version?

Could you write a step by step way to reproduce your issue?

**Comment by jackfranklin** [comment]
Hey, sorry I was so slow and never replied! I just added this plugin today and it works fine !
