### ISSUE TITLE
vimagit opens in location list

### ISSUE THREAD

**Issue by fpnick** [jreybert/vimagit#119]
Hi Jerome,

since upgrading to 1.7, vimagit sometimes (I know this is very vague, but I cannot specify it just yet) opens in the location list panel, rather than in a vsplit.

Is that intended somehow, or is it a bug?

Thanks,
Fabian.

**Comment by jreybert** [comment]
It is actually a bug, I reverted the faulty commit.

Thanks for the report!

**Comment by jreybert** [comment]
Could you confirm that it fixes your issue please?

**Comment by fpnick** [comment]
Sorry for the delay, I wanted to reproduce that at work which is where I noticed the issue.
It's fixed now, however now I get #122
