### ISSUE TITLE
Error detected while processing function magit#show_magit..magit#update_buffer

### ISSUE THREAD

**Issue by fpnick** [jreybert/vimagit#122]
Jerome,
now that you've fixed  #119 , I get a new error when trying to open vimagit:

> 
> Error detected while processing function magit#show_magit..magit#update_buffer..<SNR>16_airline_refresh..airline#load_theme..airline#highlig
> hter#load_theme..airline#highlighter#highlight..airline#highlighter#exec:
> line   20:
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> Error detected while processing function magit#show_magit..magit#update_buffer..<SNR>16_airline_refresh..airline#load_theme..airline#highlig
> hter#load_theme..airline#highlighter#highlight..<SNR>97_exec_separator..airline#highlighter#exec:
> line   20:
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1
> E421: Color name or number not recognized: ctermfg=-1 ctermbg=-1

I can hit enter a couple of times an then the buffer opens in a vsplit as desired. My vim-airline commit is fbd791e (current master).

Fabian.

**Comment by jreybert** [comment]
Between vim-airline e7e4769 and fbd791e, I get strange characters in the status line, but no error.

Could you please provide:
* test with vimagit only loaded plugin, and then vimagit + vim-airline only loaded  plugins
*    the version of vim or nvim
*    the version of git
*    the SHA1 of vimagit you're using
*    the OS that you're using, including terminal emulator, GUI vs non-GUI
*    a step by step command to reproduce the bug

**Comment by fpnick** [comment]
I just noticed that I get a very similar error when I use the Ctrl+P plugin.
Until I know any better, I'm gonna assume this is an airline issue and not a vimagit one. (I ran PluginUpdate on friday for the first time in a while, so pretty much everything was updated...)

You can probably close this issue for now, I'll let you know in case I should find any evidence this could be a vimagit issue.

EDIT: Indeed, reverting vim-airline to a (random) old version, solves both this issue and the one with Ctrl+P.

**Comment by jreybert** [comment]
Do you use an airline theme?

**Comment by fpnick** [comment]
Yes: let g:airline_theme='delek'

**Comment by jreybert** [comment]
I can't find any airline theme called delek.

**Comment by fpnick** [comment]
I have to admit I'm not exactly sure what that line is supposed to do in my vimrc. But removing it doesn't help either. Since I found a working commit in airline, I think I'll bisect the issue and see if that can tell me anything.

**Comment by fpnick** [comment]
Does not occur any more with vim-airline at commit 134c0204f3b947276c0e6f26f4fe426b5cba5c06
