### ISSUE TITLE
Edit -> file already open -> Abort -> New empty buffer

### ISSUE THREAD

**Issue by TamaMcGlinn** [jreybert/vimagit#128]
If you press "E" for edit over a hunk, but you have another instance of vim open on that file, a dialog opens to ask you what to do; I choose Abort, as usual, and this leaves me with a vertical split with a new empty buffer, instead of doing nothing as I would expect, and as would improve workflow.

**Comment by jreybert** [comment]
Thanks for the report.

I am surprised that I never run into that issue before.

**Comment by jreybert** [comment]
Merged in master and present in release 1.7.2
