### ISSUE TITLE
Error: Key not present in dictionary when staging, committing

### ISSUE THREAD

**Issue by TamaMcGlinn** [jreybert/vimagit#129]
When I do anything in the Magit buffer, such as stage files, CC to commit etc., I get error messages in red on the bottom (command buffer?), such as below. However, the operations do succeed.

```
Error detected while processing function magit#commit_command[20]..magit#update_buffer[61]..<SNR>30_mg_get_staged_section[6]..<SNR>30_mg_display_files
[8]..magit#state#file_get_filename_header:
line    4:
E716: Key not present in Dictionary: g
E15: Invalid expression: g:magit_git_status_code[self.status] . ': ' . self.filename
E716: Key not present in Dictionary: h
E15: Invalid expression: g:magit_git_status_code[self.status] . ': ' . self.filename
E716: Key not present in Dictionary: :
E15: Invalid expression: g:magit_git_status_code[self.status] . ': ' . self.filename
E716: Key not present in Dictionary: e
```

**Comment by jreybert** [comment]
To make it easier to reproduce, please supply the following:
* the version of vim or nvim
* the version of git
* the SHA1 of vimagit you're using
* the OS that you're using, including terminal emulator, GUI vs non-GUI
* a step by step command to reproduce the bug

**Comment by TamaMcGlinn** [comment]
```
NVIM v0.2.0-149-gaa4ef89
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/tama/code/neovim/build/config -I/home/tama/code/neovim/src -I/home/tama/code/neovim/.deps/usr/include -I/home/tama/code/neovim/.deps/usr/include -I/home/tama/code/neovim/.deps/usr/include -I/home/tama/code/neovim/.deps/usr/include -I/home/tama/code/neovim/.deps/usr/include -I/home/tama/code/neovim/.deps/usr/include -I/usr/include -I/home/tama/code/neovim/build/src/nvim/auto -I/home/tama/code/neovim/build/include
Compiled by tama@tardis
```
```
git version 2.1.4
```
```
vimagit 702cff8c76ce55b1b4e1a2879c306748bb699ed3 (4 commits behind master)
```
```
Linux tardis 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux
```
```
I have no friggin' idea. I can't get it to fail that way again. I will review this when I get back to the exact same machine, which has been left in the failing state, I think.
```

**Comment by TamaMcGlinn** [comment]
I have the reproduction steps now:

```
git clone git@github.com:TamaHobbit/dotfiles.git
cd dotfiles
git checkout magit_failure
git reset --mixed db245ec8fad
nvim -c MagitOnly
Press Control-N to select next hunk, which is adding the magit alias
Press Shift-S o stage that hunk
```

You get this error:
Error detected while processing function magit#stage_hunk[32]..magit#stage_block:
line    9:
E874: (NFA) Could not pop the stack !

**Comment by jreybert** [comment]
Hm, thanks for such report.

I did try to get in the same setup as you: same nvim and vimagit version, reproducing all your steps. I can't reproduce your issue. I may try with the same git version, but I don't think it is related.

> Press C-S o stage that hunk

Do you mean `Shift-S` or did you map `C-S` for stage?

**Comment by TamaMcGlinn** [comment]
Indeed, Shift-S.

I have it reproducible on a second machine; it has the exact same nvim & git version, but is on Vimagit commit 5921ef4230167e5208c4c97bff41bdc1d4538c54 (up-to-date with origin/master now)

It's the same debian build, just with more recent security patches:
Linux serenity 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

**Comment by jreybert** [comment]
Thanks for keeping up with this bug. I will try again to reproduce.
If you have time, you may try to reproduce the bug with no other plugin than vimagit loaded, to discard any problem with other plugin.

**Comment by TamaMcGlinn** [comment]
I think next I will try to get it reproduced in a virtual box, because then I can send you the virtual box file and you can debug it on that system.

**Comment by deftpunk** [comment]
I was seeing this same error after making some updates to my init.vim - installed vim-textobj-user, vim-textobj-python, [splitjoin](https://github.com/AndrewRadev/splitjoin.vim) & added a leader mapping of MagitOnly.

I backed out the changes, then added them back one at a time, excepting [splitjoin](https://github.com/AndrewRadev/splitjoin.vim), and now do not have any errors ... <shrug>  I have not tried to add [splitjoin](https://github.com/AndrewRadev/splitjoin.vim) back as i rarely use it.

**Comment by jreybert** [comment]
@deftpunk I can't reproduce your bug, even with splitjoin installed.

Would you mind to try with splitjoin again, and fill following points:
*    the version of vim or nvim
*    the version of git
*    the SHA1 of vimagit you're using
*    the OS that you're using, including terminal emulator, GUI vs non-GUI
*    a step by step command to reproduce the bug

Thanks!
