### ISSUE TITLE
Change 'S' behavior in 'Commit message'

### ISSUE THREAD

**Issue by ramok** [jreybert/vimagit#131]
I use 'S' in 'Commit message' I get "Error while staging". 

It is possible in 'Commit message' return default behavior of 'S', i.e 'Delete lines and start insert'? Or do it via configuration variable?

I heavy use 'S', and this error annoying :(

**Comment by jreybert** [comment]
This is a subject I am thinking on since several months. It make sense, I just want to do it right (.i.e without introducing bugs).

**Comment by jreybert** [comment]
@tuddman @ramok could you give a try to `next` branch. Mappings now have different behavior depending on the cursor position.

**Comment by ramok** [comment]
Just try it. Perfectly working for me. Thank you! :)
