### ISSUE TITLE
Feature: Auto-close magit buffer/window on clean state

### ISSUE THREAD

**Issue by sebastianst** [jreybert/vimagit#132]
It would be great to have an option to let Magit automatically close its buffer or window if, after a commit, the repo state is clean, i.e. there are no more diffs.
If magit was opened with `:Magit`, it should close its window, if it was opened with `:MagitOnly`, it should wipe the buffer and show the previous buffer in the same window.

BTW, this also relates to a request regarding the `q` shortcut in a magit buffer: If this buffer was opened with `:MagitOnly`, it currently closes the window. Instead, it should behave like said before and show the previous buffer instead of closing the window.

**Comment by jreybert** [comment]
Thanks for your ticket, I really like such clear improvement request 👍 .

I agree with both requests, I'll do it when I find some time.

**Comment by jreybert** [comment]
I splitted your issue in a sub issue. Could you please give a try to #137 ?

**Comment by jreybert** [comment]
@sebastianst could you please give a try to branch `next`, setting the option `g:magit_auto_close` to 1
