### ISSUE TITLE
feature request: merginal integration

### ISSUE THREAD

**Issue by sfahlberg** [jreybert/vimagit#133]
unless I missed some way to switch branches, I think it would be awesome if you could integrate with merginal, or figure out a way improve on what they do

**Comment by jreybert** [comment]
Branch management in vimagit is in my radar list since the beginning of vimagit. It is quite a a big feature. I'll give a look to merginal, but I had in mind to handle branches internally.

**Comment by jreybert** [comment]
Duplicated by #141
