### ISSUE TITLE
issue with vimagit buffer

### ISSUE THREAD

**Issue by sfahlberg** [jreybert/vimagit#134]
when I open magit and type `?` for the options, I get the following error ```Error detected while processing function magit#toggle_help[2]..magit#update_buffer[66]..magit#utils#clear_undo:
line    5:
E382: Cannot write, 'buftype' option is set```

any thoughts on how to rectify this?

**Comment by jreybert** [comment]
To make it easier to reproduce, please supply the following:
* the version of vim or nvim
* the version of git
* the SHA1 of vimagit you're using
* the OS that you're using, including terminal emulator, GUI vs non-GUI
* a step by step command to reproduce the bug

**Comment by sfahlberg** [comment]
NVIM 0.1.7
git version 2.8.4 (Apple Git-73)
hub version 2.2.9
vimagit: 5921ef4230167e5208c4c97bff41bdc1d4538c54
using iterm2, Build 3.0.14
El Capitan, version 10.11.6

in order to reproduce, simply type `:Magit`. The error will display then. It will continue displaying if you type `?`

Merci!

**Comment by sfahlberg** [comment]
I figured it out- it was this line: `inoremap <C-[> <ESC>:w<CR>`.

**Comment by jreybert** [comment]
Hi @sfahlberg , sorry for the delay.

I am not sure to understand your last comment: your issue was caused by a mapping in your own configuration? If so, could you please close this issue?

Thanks

**Comment by sfahlberg** [comment]
yes, that's right
