### ISSUE TITLE
issue with .gitmessage template 

### ISSUE THREAD

**Issue by nibrunie** [jreybert/vimagit#135]
When using git commit.template, If a change is staged after a commit message has already been started the message template defined in .gitmessage is duplicated in  the "Commit message" section.

How to reproduce the bug
-> have an explicit git message template defined in an accessible .gitmessage file registered in git commit.template field
-> Stage a change
-> Start a commit message (e.g. with <CC>)
-> Stage an other change => commit.template will be duplicated

bug is visible on branch: next, commit 95f8ad71

**Comment by jreybert** [comment]
Merged in master and present in release 1.7.2
