### ISSUE TITLE
'q' in MagitOnly buffer should show the previous buffer

### ISSUE THREAD

**Issue by jreybert** [jreybert/vimagit#137]
BTW, this also relates to a request regarding the q shortcut in a magit buffer: If this buffer was opened with :MagitOnly, it currently closes the window. Instead, it should behave like said before and show the previous buffer instead of closing the window.

Seen in #132 and #130

**Comment by jreybert** [comment]
@guyzmo @sebastianst could you please try the `dev/close` branch please? thanks for your feedback.

**Comment by sebastianst** [comment]
`q` now leaves the window open when magit was opened with `:MagitOnly`. Thank you!
However, after committing the last change and the repo state is clean, the window still remains open and doesn't close automatically (#132).

**Comment by jreybert** [comment]
@sebastianst glad it fits your need. And I did not forgot #132, I just split this issue up.

**Comment by guyzmo** [comment]
♥

**Comment by jreybert** [comment]
Merged in master and present in release 1.7.2
