### ISSUE TITLE
Error: multiple empty commits

### ISSUE THREAD

**Issue by sebastianst** [jreybert/vimagit#138]
With the recent version of vimagit, I suddenly get several pop-ups in gvim asking whether I want to go ahead with an empty commit. I choose *no* every time and the commit history is as expected: The actual commit that I prepared with vimagit got committed. If I choose *yes*, after the normal commit there come several empty commits with empty commit message.

Any ideas what causes this? It just happens recently after I upgraded vimagit...

**Comment by jreybert** [comment]
* What version of vimagit are you using (SHA1)?
* Does it happens only with gvim, or also with vim?

**Comment by axlebedev** [comment]
1. Bug exists at `0549731101b8c341d9732d3e9d74c6ba09bbf3ea add github issue template`
2. Gvim only

**Comment by KeithScheiwiller** [comment]
I can confirm this is also happening at `0549731101b8c341d9732d3e9d74c6ba09bbf3ea` in neovim (via terminal). It seems to be a differing number of such empty prompts each time it happens.

**Comment by jreybert** [comment]
Thanks for the update, I need to find time and track it down (damned Zelda...)

**Comment by ntcong** [comment]
After a bit of bisect, I found the commit that introduced the problem: 36c277ea2e8e40755e9f864e4baa8d74b3ce4495

So it's the problem when we use :wq to commit, I switch to using CC to commit and it works without any notice. It weird that I don't have any problem with this until now, so maybe some changes in internal neovim/vim broke the plugin.

Also I think that wq should commit and close vimagit :)

**Comment by jreybert** [comment]
Many thanks to @ntcong finding this sneaky bug!

I am just worried because I am not able to reproduce this bug, with vim or neovim, even if I see the multiple autocmd...

And for the `:wq` behavior, I am not sure. In my mind, `:wq` can be seen as "Write commit and close commit mode". But I agree it is weird because `:w` does the same thing.
