### ISSUE TITLE
Syntax highlighting in diff

### ISSUE THREAD

**Issue by kristijanhusak** [jreybert/vimagit#144]
What colors from color scheme is used to display the diff?
It looks like it's not using DiffAdd, DiffChange, etc.
I would like to update it because my color scheme setup gives some strange results, where added line is red and removed one is purple.

**Comment by jreybert** [comment]
I import the syntax file `syntax/diff.vim`, and declare that everything in a hunk is a diff syntax.

I should be standard colors. Could you search if you have a `syntax/diff.vim` file in your `.vim/` path.

**Comment by kristijanhusak** [comment]
Yeah it's using `diffRemoved` and `diffAdded` highlighting groups, i thought it's using the ones that vimdiff uses. So it's messed up in my color scheme. Thanks for help, keep up the good work!
