### ISSUE TITLE
Adding empty .gitignore

### ISSUE THREAD

**Issue by robphoenix** [jreybert/vimagit#145]
## Short description of the problem

When I use vimagit in my dotfiles directory it adds an empty `.gitignore` file. I have a global gitignore file called `gitignore` that I alias to `~/.gitignore`.

## Steps to reproduce

Make a change in [dotfiles](https://github.com/robphoenix/dotfiles) directory. Stage change with `S`

## Environment

* `vim` or `nvim` version
NVIM v0.2.1-dev

* `git` version
git version 2.14.2

* current vimagit version or (or SHA1)
https://github.com/jreybert/vimagit/commit/b3cbfc5b4f86cc970c1a6ab3f8ca10a69d9ff39a

* OS
Ubuntu 16.04

* terminal or gvim
terminal

**Comment by jreybert** [comment]
Hi @robphoenix ,

I can't reproduce your issue, even when I try from your repository.

Did you type <kbd>I</kbd> while you were staging? Typing <kbd>I</kbd> ignores the file under your cursor. By ignoring, I mean it appends the filename in `.gitignore` file (creating it if it does not exists). But in this case, I wonder how it could be empty...

**Comment by robphoenix** [comment]
Hey @jreybert 

Of course, now that I've raised the issue, I can't reproduce it either! :man_shrugging: 

It could well be that I typed `I`,  that makes sense, and now that I'm unable to reproduce it I'm starting to doubt myself that it was an empty `.gitignore`. Oh well, sorry for the time suck, I appreciate you going to the effort for the issue anyway. And thanks for the plugin! :sparkles:
