### ISSUE TITLE
E874: (NFA) Could not pop the stack !

### ISSUE THREAD

**Issue by sivakov512** [jreybert/vimagit#156]
## Short description of the problem
Can not stage hunk

## Steps to reproduce
- Make some changes
- Add one hunk
- Commit
- Try stage another hunk

## Environment

* `vim` or `nvim` version
`NVIM v0.2.2`

* `git` version
`git version 2.15.1`

* current vimagit version or (or SHA1)
latest

* OS
Void Linux

* terminal or gvim
xfce4-terminal

## Screenshot with problem
![image](https://user-images.githubusercontent.com/10251687/33540761-32dd25c2-d918-11e7-94eb-d820c7c02d7d.png)

**Comment by jreybert** [comment]
I can see that you have `magit#stage_vselect` in your backtrace: do you try to stage a visual selection?

Could you provide the key typed at each step?

Thanks

**Comment by jreybert** [comment]
ping @cryptomaniac512

**Comment by sivakov512** [comment]
Oh, sorry
as far as I understand, git does not allow me to stage any hunks. I observe a similar one in magit, but magit stage all hunk instead of error

**Comment by jreybert** [comment]
Did finally succeeded to stage some hunks with vimagit?

You say you can't stage by hunk with magit too, do you think the problem is not in vimagit but in your environment? In that case, I am interested to understand your environment to maybe handle it wisely in vimagit.

**Comment by sivakov512** [comment]
I don't use vim now (because I can't live without all magit features), but I will try to reproduce it in the coming days.

**Comment by sivakov512** [comment]
I still have not found the time to check it out and I'm not sure I'll find it. Sorry :(

**Comment by wilt00** [comment]
I think I have a repro for this bug:

* Initialize a git repository
* Paste the following text into a file:

```vim

set directory=~/.config/nvim/backups,~/.vim/tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set wildignore+=*/.git/*,*/tmp/*,*.swp,*.o,*/.hg/*,*/.svn/*,*/.DS_Store,*~,*.pyc

set backspace=eol,start,indent  " indent:   allow backspacing over autoindent
                                " eol:      allow backspacing over linebreaks
                                " start:    allow backspacing over start of
                                "            insert
set noerrorbells

" }}}
```

* Commit this file to the repository
* Modify the file so it looks like this:

```vim

set directory=~/.config/nvim/backups,~/.vim/tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set wildignore+=*/.git/*,*/tmp/*,*.swp,*.o,*/.hg/*,*/.svn/*,*/.DS_Store,*~,*.pyc

set backspace=eol,start,indent  " indent:   allow backspacing over autoindent
" eol:      allow backspacing over linebreaks
" start:    allow backspacing over start of
"            insert
set noerrorbells

" }}}
```

* Attempt to stage change in Magit. I get this error:

```
Error detected while processing function <SNR>100_nmapping_wrapper[2]..magit#stage_hunk[32]..magit#stage_block:
line    9:
E874: (NFA) Could not pop the stack !
Press ENTER or type command to continue
```

nvim v0.3.2-dev
vimagit 1.7.2 (according to the changelog file)
git 2.18.0
Bash on Ubuntu on Windows
Terminal (Mintty 2.7.9 x86_64-pc-cygwin, wsltty 1.7.9)

**Comment by jreybert** [comment]
Thanks @wilt00 for your effort trying to setup a simple to reproduce this error.
This is sad, but I can't reproduce following your steps. I match your configuration for nvim, vimagit and git versions.
I doubt it could come from Ubuntu or the terminal, but at this point, who knows...

The only way I see to continue this investigation would be for you to let me try with a remote access on your machine (ssh, or anything else).

**Comment by akrejczinger** [comment]
I also had the same issue.
I managed to reproduce the issue in a Docker container: `docker run --rm -it hoborg/vimagit_bug_156`
Then follow the instructions by @wilt00 
I hope it helps fix the problem.

**Comment by jreybert** [comment]
@akrejczinger thanks a lot for the docker image.

I never used docker, how am I supposed to get your docker image hoborg/vimagit_bug_156 ?

**Comment by akrejczinger** [comment]
@jreybert 
- install docker: instructions [here](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository) for ubuntu
- run the command `docker run --rm -it hoborg/vimagit_bug_156`. It will download the image from Docker Hub automatically if it's not found on your machine already.

Docker hub link: https://hub.docker.com/r/hoborg/vimagit_bug_156/
The dockerfile is available in my repository: https://github.com/akrejczinger/vimagit_bug_156

**Comment by jreybert** [comment]
I can finnaly reproduce your issue! Thanks a lot @akrejczinger for your docker image.

**Comment by jreybert** [comment]
Finally, I got it! Thanks @akrejczinger for the docker, thanks @wilt00 for the step by step, and thanks @sivakov512 for opening this issue.

It was actually very fast to fix, but a little bit harder to introduce this case in the test suite!

Would you mind test the branch `next` so I can cherry pick this into master?

**Comment by wilt00** [comment]
Looks fixed! Thanks for all your work on this @jreybert !

**Comment by jreybert** [comment]
Finally, I got it! Thanks @akrejczinger for the docker, thanks @wilt00 for the step by step, and thanks @sivakov512 for opening this issue.

It was actually very fast to fix, but a little bit harder to introduce this case in the test suite!

Would you mind test the branch `next` so I can cherry pick this into master?
