### ISSUE TITLE
Error detected while processing function <SNR>96_nmapping_wrapper[2]..magit#stage_hunk[32]..magit#stage_block

### ISSUE THREAD

**Issue by iaia** [jreybert/vimagit#168]
## Short description of the problem

```
Unstaged changes
================

modified: .zshrc
@@ -118,3 +118,5 @@ if [ -f '/Users/xxxx/google-cloud-sdk/path.zsh.inc' ]; then source '/
 if [ -f '/Users/xxxx/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/xxxx/google-cloud-sdk/completion.zsh.inc'; fi
 
 export PATH="${HOME}/Library/flutter/bin:$PATH"
+
+alias bu='bundle update'
```

type `S`

```
Error detected while processing function <SNR>96_nmapping_wrapper[2]..magit#stage_hunk[32]..magit#stage_block:
line    9:
E944: Reverse range in character class
E944: Reverse range in character class
Press ENTER or type command to continue
```

## Environment

* `VIM - Vi IMproved 8.1 (2018 May 17, compiled May 24 2018 10:14:40)`
* `git version 2.16.2`
* current vimagit version or (or SHA1): `1.7.2`
* OS: `macOS 10.13.4`
* terminal

**Comment by jreybert** [comment]
I can't reproduce your issue. Could you please:
* add to this issue all the vimagit options set in your vimrc
* copy paste the exact vimagit buffer (including the empty lines at the end of this buffer). I am actually wondering why I don't see two empty lines after your line: `+alias bu='bundle update'`

**Comment by iaia** [comment]
> add to this issue all the vimagit options set in your vimrc

```
" vimagit
let g:magit_default_fold_level = 2
let g:magit_default_sections = ['global_help', 'info', 'unstaged', 'staged', 'commit']
let g:magit_discard_untracked_do_delete=1
```

> copy paste the exact vimagit buffer (including the empty lines at the end of this buffer). I am actually wondering why I don't see two empty lines after your line: +alias bu='bundle update'

```
Info
====

Repository:  /Users/xxxx/dotfiles/
Head:        master        追加
Upstream:    origin/master 修正
Push:        origin/master 修正

Press ? to display help


Unstaged changes
================

modified: .zshrc
@@ -118,3 +118,5 @@ if [ -f '/Users/xxxx/google-cloud-sdk/path.zsh.inc' ]; then source '/
 if [ -f '/Users/xxxx/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/xxxx/google-cloud-sdk/completion.zsh.inc'; fi
 
 export PATH="${HOME}/Library/flutter/bin:$PATH"
+
+alias bu='bundle update'


Staged changes
==============


```

**Comment by jreybert** [comment]
Do you have Japanese characters in place of `xxxx` in:
```
 if [ -f '/Users/xxxx/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/xxxx/google-cloud-sdk/completion.zsh.inc'; fi
```
?

**Comment by iaia** [comment]
No.

I tried another machine.

<img width="1402" alt="2018-05-28 21 30 11" src="https://user-images.githubusercontent.com/1254889/40614610-75c78672-62be-11e8-8874-d11a34054975.png">

**Comment by jreybert** [comment]
Crap, all my simple suppositions were wrong... Please keep your faulty repository with this exact state in a safe place, so we can reproduce it.

**Comment by jreybert** [comment]
Finally, thanks to another issue #156 , I also fixed your issue.

Would you mind @iaia to test the branch `next`?

**Comment by iaia** [comment]
@jreybert I tried `next` branch. Successfully added to the stages. Thank you for fix.
