### ISSUE TITLE
Magit cannot find the repo

### ISSUE THREAD

**Issue by haomeng689** [jreybert/vimagit#169]
Magit cannot find the repo. 
My vim version is 8.1 and my git version is 2.9.5 which is installed on the ~/git-2.9.5. I have made the PATH environment variable to include the ~/git-2.9.5. I did create the repo. However, Magit still cannot find the repo.

**Comment by jreybert** [comment]
Hi,

sorry for the late answer.
Do your new repo contains any commit? Or do you try to start vimagit just after the `git init` command? In the last case, this is an issue, vimagit does not handle correctly a git repo freshly init'ed.
