### ISSUE TITLE
vimagit can be very slow

### ISSUE THREAD

**Issue by mg979** [jreybert/vimagit#170]
## Short description of the problem
vimagit buffer update can take ages. It usually happens when there are a lot of changes. My guess is that it has to do with folding, because if I abort with `<C-c>` while the process is stuck, close the buffer and reopen vimagit, hunks are staged/unstaged correctly. Maybe vimagit updates the buffer while folding is active, bit by bit? In this case a possible solution would be to disable folding while updating buffer, or similar. 

## Steps to reproduce
The more text, the slower it is. It's not dependent on the number of hunks, but on how big hunks are.

## Environment
Linux Debian stable.

* `vim` or `nvim` version: vim 8.0+ (sometimes 8.1)

* `git` version: 2.11

* current vimagit version or (or SHA1): 85c25ff

* terminal or gvim: terminal

**Comment by jreybert** [comment]
Thanks for your report, this is a lead I never explored.
I'll dig around it and update this ticket if I find anything relevant.

**Comment by mg979** [comment]
Maybe it has also to do with certain filetypes, because usually it's fast. It behaved worst with dos files with very long lines and lots of tabs (a sort of table).

**Comment by jreybert** [comment]
As you mention very long lines, it reminds me that vim by itself can be very slow with long lines, because of syntax coloring.

**Comment by jreybert** [comment]
By any chance, would you have a public repository which makes vimagit slow?

Could you also test with this following setting in your vimrc:
`let g:magit_default_fold_level = 2`

**Comment by mg979** [comment]
You could try with [this commit](https://github.com/mg979/vim-xtabline/commit/f972586f6c982fbe633f9aa33f0d73241e5f7f59), make a branch out of it, then `git reset --hard HEAD^` and squash the original branch without committing, so that you can have the unstaged commit in vimagit.

The README.md file takes a lot to be staged/unstaged, but hit `<c-c>`, quit vimagit, and enter again, you'll see that the operation is done, and vimagit loads fast as usual.

Edit: `let g:magit_default_fold_level = 2` doesn't help.

**Comment by jreybert** [comment]
Excellent, thanks a lot for your input!

**Comment by jreybert** [comment]
Hourray! It has been fixed!

Thanks a lot for all your input, it wouldn't have been possible without that.

Could you try the branch next?

**Comment by mg979** [comment]
Thanks, I'll be able to test it in a few days because I have only Windows in this machine and gvim there doesn't seem to have this problem (even if it's slow on its own because command line stuff seems to much slower on Windows anyway), but I'm confident it will work :)

**Comment by mg979** [comment]
Ok I tested it and it seems perfect to me, much more responsive, thanks!
