### ISSUE TITLE
Error after install when open `Magit`

### ISSUE THREAD

**Issue by drazde** [jreybert/vimagit#174]
## Short description of the problem
When I do `:Magit` it give me this error:
![immagine](https://user-images.githubusercontent.com/2643448/58259417-c4074580-7d74-11e9-9b03-c29083ed0037.png)

## Steps to reproduce
1. open a file under git 
2. do `:Magit`

## Environment
* vim 8.1 x64
* git 2.19.1 Windows
* vimagit (latest release 1.7.3, I use  `Plug`)
* Windows 10
* gvim

**Comment by jreybert** [comment]
Hi, sorry for the delay, I postponed your issue first, then I shamely forgot it...

- is your file in a git repository
- what is the full path of your file, and the full path of your git repo?
- open your file with vim, and give me the output output of the commands
  - `:expand("%:p")`
  - `:call getcwd()`

**Comment by drazde** [comment]
No problem :)
>     * is your file in a git repository
Yes
>     * what is the full path of your file, and the full path of your git repo?
`R:\test\prova.txt`

>     * open your file with vim, and give me the output output of the commands
>       
>       :expand("%:p")
  `E492: Non è un comando dell'editor: expand("%:p")`
Is not a command of the editor...
>       :call getcwd()
Nothing result

**Comment by jreybert** [comment]
Crap, my viml is rusted.

Could you give me the output of :
- `:echo getcwd()`
- `:echo expand("%:p")`

**Comment by drazde** [comment]
> Crap, my viml is rusted.
Hihi ok, it seemed strange

>     * `:echo getcwd()`
R:\test

>     * `:echo expand("%:p")`
R:\test\prova.txt

**Comment by sun617** [comment]
has any `echo` in your fish config?
remove that `echo` may be resolve the problem

**Comment by drazde** [comment]
> 
> 
> has any `echo` in your fish config?
> remove that `echo` may be resolve the problem

I have this error on Windows not on Linux, do you mean fish shell?

**Comment by jreybert** [comment]
@drazde sorry, I do not have any idea about your problem right now, and it is difficult to test on windows. Did you try on another system with windows 10? Do you have the same issue?
Did you try on another repository, in another in your system?

**Comment by drazde** [comment]
> @drazde sorry, I do not have any idea about your problem right now, and it is difficult to test on windows. Did you try on another system with windows 10? Do you have the same issue?

I use both Linux and Windows, on linux is ok on Windows I have that problem 

> Did you try on another repository, in another in your system?
Yes the same problem. 

My home dir have space in the path coud be a problem?

**Comment by jreybert** [comment]
spaces in path have been a problem, and fixed a long time ago on Linux. Yes, it may be a problem on windows too, and the fix may be different.

Do you have a way to test the exact same repository in a path without space?

**Comment by drazde** [comment]
I don't understand what could have happened, 
but I ave no more the problem!

I close the bug, but I don't underestand what has changed

**Comment by satish77** [comment]
vim 8.2.3397 on windows 10 gives the folllowing on :Magit
![image](https://user-images.githubusercontent.com/1807923/193941524-176f003a-d997-4b0b-9a0a-13b88bbf0c88.png)
