### ISSUE TITLE
 Is this plugin still alive?

### ISSUE THREAD

**Issue by glepnir** [jreybert/vimagit#175]
HI ， sorry for broken issue template， i switched vimagit。but i saw it didnt update a long time.so i want know this pluin still alive?

**Comment by jreybert** [comment]
It is.

vimagit is very stable. I have lot of ideas for new features, but no time for it.

I try to fix any stability issue.

**Comment by glepnir** [comment]
@jreybert ...all right i think its not alive. i also has lots of idea . i forked it and make Recent commits show in floatwindow...

**Comment by glepnir** [comment]
this is my make more like emacs magit
![1](https://user-images.githubusercontent.com/41671631/61779507-63a78980-ae33-11e9-89e4-95ae7e299622.png)

by the way how can i set the magit buffer on right?

**Comment by jreybert** [comment]
Not sure to understand your conception of alive.

On my side, I prefer to let the plugin stable, and add new feature only when I am sure that it does not break anything. It asks a lot of time, especially expending the test suite for every new feature.

When I heard about the floating window, I thought it would maybe be useful for vimagit.
I would love to hear your ideas, maybe a good place to discuss that is the gitter room: https://gitter.im/jreybert/vimagit

Your fork is a bit brutal: rename of the project, no git history from the original project, no license on the readme... Considerig the git log of your project, it is not possible to backport your modifications as is.

**Comment by glepnir** [comment]
Because you haven't responded to this issue for a long time, I thought it was dead. So I am trying some of my ideas, if you agree, I would very much like to submit pr。 i added this gitter.but i found the latest talk is 2018....I did not intend to promote my fork. Because I can't finish my thoughts. My vimscript is just primary，by the way i set it on right :)

**Comment by jreybert** [comment]
OK, I understand better now.

Your modifications touch the core of the vimagit GUI, it will ask a lot of work to make it stable.
