### ISSUE TITLE
User-configured diff.noprefix breaks stage / unstage

### ISSUE THREAD

**Issue by wwade** [jreybert/vimagit#176]
## Short description of the problem
When `diff.noprefix` is enabled (e.g. `git config --local diff.noprefix True`), stage / unstage fails to apply.

Error output:
[vimagit-error.txt](https://github.com/jreybert/vimagit/files/3424892/vimagit-error.txt)

## Steps to reproduce
1. Enable diff.noprefix: `git config --local diff.noprefix True`.
2. Using magit, attempt to stage a change.

## Environment

* `vim` 8.0.1788
* `git` 2.19.1
* vimagit 1.7.3 91b947cceb7f1c7d005f6b1941478802c4b096db
* OS Fedora 18
* terminal

**Comment by jreybert** [comment]
Fixed, thanks
