### ISSUE TITLE
Add Ex command to unhide all hunks at magit opening

### ISSUE THREAD

**Issue by hoschi** [jreybert/vimagit#18]
This would be really usefull to get a quick overview. It should be an opt-in feature, because this can be slow with huge changes, I think.

**Comment by jreybert** [comment]
Hi hoschi, 

could you explain what you mean by diff mode? 

If you mean side by side diff, please could you provide some example (a schema for example) describing how you imagine such mode with magit workflow. 

Thanks

**Comment by hoschi** [comment]
I mean all file hunks are shown and expanded. This way you don't have to go
to each file  and press enter followed by `zO` to expand all hunks of that
file.

Jérôme Reybert notifications@github.com schrieb am Do., 15. Okt. 2015
20:42:

**Comment by hoschi** [comment]
Sorry, 'overview' isn't a good word for that kind of view. I meant it
should be an overview of _all_ changes as diff.

Stefan Gojan vollekannehoschi@gmail.com schrieb am Do., 15. Okt. 2015
23:04:

**Comment by jreybert** [comment]
OK! That's an easy one :) I reword the issue title.

It'll be in next release then.

Thanks for the feedback.

**Comment by hoschi** [comment]
:clap:
cool you like the idea :)

**Comment by hoschi** [comment]
I updated the plugin and configured it to show all files/hunk expanded, works like a charm :+1:

**Comment by jreybert** [comment]
glad to hear it works. I am curious, did you use global parameters or show_magi() parameter with a new mapping?

**Comment by hoschi** [comment]
I used the global parameters to make a "show all hunks" (default) version. When I run into performance or "too much diff" problems, I think about how to use show_magit() function to fix this.

**Comment by jreybert** [comment]
I have several ideas for performance issues. 

For example, add a configuration parameter to never show untracked files (see #28).

Another optimization should also appear soon in next, optimizing performance for closed files.
