### ISSUE TITLE
after addint a git submodule vimagit doesn't work anymore

### ISSUE THREAD

**Issue by kronikpillow** [jreybert/vimagit#187]
## Short description of the problem
```
Error detected while processing function magit#show_magit[148]..magit#update_buffer[59]..magit#state#update[14]..magit#utils#refresh_submodule_list[1]..magit#git#submodule_status[1]..magit#sys#system:
line    5:
E605: Exception not caught: shell_error
Press ENTER or type command to continue
```

## Steps to reproduce
install vimagit, add different git repository as a a gitsubmodule 
## Environment
* nvim 0.4.3-2
* git 2.26.0-1
* vimagit commit bf7b16e
* Arch
* st

**Comment by arafel** [comment]
Hi! Just to check something - the module you're adding the submodule into (i.e. the parent), does that have any commits in it? The release Vimagit has a bug which will cause a problem if it's not been committed to (https://github.com/jreybert/vimagit/pull/192).

If that's not the case then "git status" and "git submodule status" might well be useful. Also - if you have chance - please could you try running:

```
git rev-parse --abbref-rev HEAD
git count-objects -v
```

and see if those both succeed?

I'm not the author, but I've just tried using a git repo with a submodule and it worked after I fixed the bug mentioned at the top, so I thought I'd try and help @jreybert out a bit while the code's still in my head. :)

**Comment by kronikpillow** [comment]
mate I honestly don't remember. .. I made this thread in march ... It's november ... but thanks for the reply ... when I have time I'll try to replicate the problem and see if it still is present

**Comment by jreybert** [comment]
It seems that @arafel PR fixed the issue. I close this issue, reopen it if you still encounter a submodule issue.
