### ISSUE TITLE
<tab> for Toggling code

### ISSUE THREAD

**Issue by joshmedeski** [jreybert/vimagit#190]
Feature request: Can <tab> be bound to toggle the code? It's the key that I'm used to and I think it's a sensible default binding.

**Comment by arafel** [comment]
Hi - apologies, it might be obvious to everyone else, but - what do you mean by 'toggling the code'? What code...?

Thanks :)

**Comment by joshmedeski** [comment]
I meant the code folding inside the vimagit status buffer (to hide and show hunks).

But I decided not to use vimagit in my workflow so I'll close the issue.
