### ISSUE TITLE
Very slow using my neovim config

### ISSUE THREAD

**Issue by LordMZTE** [jreybert/vimagit#193]
## Short description of the problem
vimagit is incredibly slow, even opening the vimagit buffer using
`:Magit` takes a good 5 seconds.

## Steps to reproduce
- Use [my nvim config](https://github.com/LordMZTE/dotfiles/blob/master/nvim/init.vim)
- Use the `:Magit` command
- Wait

## Environment

* `vim` or `nvim` version: `NVIM v0.4.4`
* `git` version: `2.31.0`
* current vimagit version or (or SHA1): `aaf1278f03e866f0b978d4b0f0cc7084db251129`
* OS: `manjaro linux`
* terminal or gvim: tmux in alacritty

**Comment by jreybert** [comment]
I fixed an issue of very slow update due to submodules in 421ecc9, which has been merged in master in June 2021. Do you still experience very slow update?

**Comment by LordMZTE** [comment]
Seems to be fixed!
