### ISSUE TITLE
jump_to function fails when jumping to a dirty existing buffer

### ISSUE THREAD

**Issue by klement** [jreybert/vimagit#194]
My situation:

I have a file with multiple changes and I want to edit some of them. So I'm walking change by change and pressing E to open my file. I do the change in the file and switch back to magit buffer, but when I press E again on the next change, it throws an exception:

```
Error detected while processing function <SNR>94_nmapping_wrapper[2]..magit#jump_to:                                                                         
line   29:                                                                                                                                                   
E608: Cannot :throw exceptions with 'Vim' prefix                                                                                                             
Error detected while processing function <SNR>94_nmapping_wrapper:                                                                                           
line    2:                                                                                                                                                   
E171: Missing :endif   
```

this goes away if I save the buffer before doing this. So I wonder if magit could

1.) not do this if it's moving within the same file
-or-
2.) respect autowrite and write the buffer before reopening it

Thanks.

**Comment by jreybert** [comment]
Hi, after more a year of silence, I decided to come back to vimagit. Sorry for the long time without support.

Your issue is larger than autowrite. If you still encounter a problem, please let me know, I did not try with autowrite.

I think you issue is fixed in branch next, with the warm cooked commit.
