### ISSUE TITLE
Idea: configure if comments in gitmessage template should be shown

### ISSUE THREAD

**Issue by teutat3s** [jreybert/vimagit#196]
Thank you for this handy vim plugin!

I'd like to use a git commit message template `~/.gitmessage`, that contains comments. I use these comments to guide me through writing the commit message, much like GitHub issue templates. Currently only uncommented lines from that `~/.gitmessage` make it into the `vimagit` commit message buffer. Maybe there's already a way to achieve what I want or would this require some code change?

**Comment by jreybert** [comment]
Hi, thanks for your issue.

Could you try the branch `next` please?

I think to try branch `next` for 2 weeks, then integrate in branch `master`.

**Comment by teutat3s** [comment]
Wow this was fast, thank you. I'll try it out and report back.

**Comment by teutat3s** [comment]
First impression: great! Comments are there when changing from staging to commit mode.

Somehow they get included in the final commit message, though:

EDIT: this is the part of the output of `git log`
```
commit e3dd667fc999b71b5dbc1bf6bb8adeac575fcfd7 (HEAD -> teutat3s)
Author: teutat3s <xxx@xxxx.xxx>
Date:   Wed May 4 18:21:37 2022 +0200

    # Title: Summary, imperative, start upper case, don't end with a period
    # No more than 50 chars. #### 50 chars is here:  #
    #
    Use forked nix-autobahn with dependency fixes

    # ^ Remember ending with an extra blank line
    # Body: Explain *what* and *why* (not *how*). Include issue number.
    # Wrap at 72 chars. ################################## which is here:  #
    #

    # ^ Remember ending with an extra blank line
    # At the end: Include Co-authored-by for all contributors.
    #
    # Co-authored-by: Example Name <email@example.com>
```

**Comment by jreybert** [comment]
Indeed, git does not apply cleanup when commit input comes from a file... I need to workaround that.

**Comment by jreybert** [comment]
Last commit should fix your issue.

**Comment by teutat3s** [comment]
Yes now it works as expected. Great! Thank you.
