### ISSUE TITLE
q to close window

### ISSUE THREAD

**Issue by firedev** [jreybert/vimagit#2]
Hi,

Thank you for porting Magit, the only thing I liked about Emacs. Could you please add a `q` shortcut to close window like it's done in NERDTree, Fugitive, vim-plug and others?

Thanks.

**Comment by jreybert** [comment]
I was this close to move to emacs, just for magit :)

**Comment by firedev** [comment]
Thanks. Couldn't survive all the key-bindings in Emacs.
