### ISSUE TITLE
Vertical tracking diff split view

### ISSUE THREAD

**Issue by jordwalke** [jreybert/vimagit#20]
Is it possible to view the diffs in a vertical diff split?

**Comment by jreybert** [comment]
I am not comfortable with this feature:
- With my actual vim knowledge, I don't think it is possible to provide a side by side diff view in the main vimagit window.
- The way to add this feature would to display two more windows when user want to see a diff split. I feel it does not integrate well in the actual worflow, where you do all staging stuff in one window, then you don't have to switch between windows.
- I don't know how vim behave to update non current buffer content.

Anyway, you are not the first one to ask this feature. If you have some time, I would be interested to read a precise description of what you are expecting, and how you would use it.

In some next release, vimagit should provide a word-diff visualization (see #21).

**Comment by jreybert** [comment]
As I don't plan to implement this (soon or nether...), I close the ticket.

If you are OK to explain a clear workflow, I would like to see it. In this case, feel free to reopen the ticket.
