### ISSUE TITLE
feature: let vimagit handle multiple git repository

### ISSUE THREAD

**Issue by zimski** [jreybert/vimagit#29]
Hello,
Firstly, i want to thank you for this valuable plugin.

When i changes directories inside vim (switch between projects) Magit not follow me.
1.i am in projet 1, magit works perfectly
2. change project ( i use sessions)
3. when i fire up again `magit` it's still show me the previous git of the previous project.

to switch correctly i need to exit vim and restart it.

If you can show me how reset `magit` when i change directories.

thx.

**Comment by jreybert** [comment]
Hi Zimski,

actually, this non feature is not described, and should be clearly statuated in the README.

So no, vimagit does not support several git project for the moment. I have some ideas for how implement it, I just need to find some time.

vimagit still miss a lot of cool features, I can't say when I will add this one.

I will chhose a set of features for next release soon, I will see if I can include this feature.

Stay tune ! :)

**Comment by zimski** [comment]
Hi JreyBert,
thanks for the quick reply.
I am a big noob in `vim script` but i will learn this this and it will be cool if i can contribute to this plugin with this feature.

I you have some ideas how to do this or you see this feature, let me know.

**Comment by zimski** [comment]
I found a quick fix fot this issue/feature.

I am already using a  `vim-rooter` plugin who will set the right `pwd` for me ( he chooses the parent folder where he founds the `.git`

so i commented in `autoloads/magit/utils.vim` some commands

```
" execute s:magit_cd_cmd . magit#git#top_dir()
....
" execute s:magit_cd_cmd . dir
```

And now it works fine :)

**Comment by jreybert** [comment]
I believe that this feature is now added in branch dev/multiple_repo.

I'll wait for your feedback before merging it in next.

**Comment by zimski** [comment]
Hi,
Nice to see this feature,
I get some general advices about the commit message format:
- try to have a small commit message (< 80 char)
- For extra info you can append new line and add the extra info
- No need to have the updated files in the commit message, Git handle this perfectly ;)
- Add the Issues number at the beginning of the commit message
- try to have one commit for one fix. this will make an easy revert if needed.

For instance:

```
[#44,#34,#29]: Support multiple git repo

- Add also the ability to open a magit buffer from a netrw buffer
```

I will test this PR tomorrow and i will give you my feedback.

Great work :)

**Comment by jreybert** [comment]
Hi zimski,

I hope you'll enjoy the feature. Please test it carefully, and chase the corner cases :)

> try to have a small commit message (< 80 char)
> For extra info you can append new line and add the extra info

I am lazy, and it helps me writing release notes (I am a guilty huge fan of git log --oneline)

> No need to have the updated files in the commit message, Git handle this perfectly ;)

Same as previsou point. Knowing the touched file(s) gives me a lot of informations about the commit.

> Add the Issues number at the beginning of the commit message

The issue number is not an important information. I prefer put it at the end of my long long lines, getting real information visible.

> try to have one commit for one fix. this will make an easy revert if needed.

These 3 fixes are duplicates.

**Comment by zimski** [comment]
Hi,
We are all lazy, but if you like to get contribution and make your git clean.. you need to comply to some best practices, in the beautiful open source world we are not alone ;) and the duty of the contributor/maintainer is to make his contribution simple to understand and make easier the futur contributions. 

The number of issue is important, imagine after 6 months you need to get more info about the issue that is fixed by one specific commit, have the issue number in the commit make it easier.

I understand some times, all this rules are boring but you will see the benefit when you will have more commits and more contributors.

**Comment by jreybert** [comment]
I appreciate your concern.

I know this is important to make the source and the repository easy and pleasant to use for enthusiast contributors.

I may be completely blind, but I think this project respects number of good practices.

Each project define its own rules, some useful, other reflecting maintainer habits. Anyway, I don't critic the rules you described,  they are known to be good rules.

Limit commit title to 80 characters is a good rule. Another good rule is to have all information in commit title. As these two good rules can't sometime work together, you must make a choice.

However, you insist about the issue tracking. I don't follow you. I have 3 tickets, all about the exact same issue (did you check the content of issues #34 and #44?). Then, I have one single commit, referencing these 3 issues in its title. What would  you expect in this case?

About referencing issues in commit message, the commit pattern you suggest do not use a command and interesting tracker feature, as github offers for instance: https://help.github.com/articles/closing-issues-via-commit-messages/

Cheers

Jérôme
