### ISSUE TITLE
Vimagit asciicast 

### ISSUE THREAD

**Issue by firedev** [jreybert/vimagit#3]
I would like to see how you are using it. 

And I am sure it should help others and to boost popularity. What do you think about recoding a short asciicast with this: https://asciinema.org/

**Comment by jreybert** [comment]
On 10/02/2015 10:34 AM, Nick Ostrovsky wrote:

> I would like to see how you are using it.
> 
> And I am sure it should help others and to boost popularity. What do 
> you think about recoding a short asciicast with this: 
> https://asciinema.org/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jreybert/vimagit/issues/3.

Sure thing! I had it in mind, I just need to find some time.

## 

Jérôme
