### ISSUE TITLE
 Uncaught exception when staging/unstaging multiple files

### ISSUE THREAD

**Issue by h3xx** [jreybert/vimagit#30]
Magit version affected: <1.4.1> 3c3baa3241f7490c3b1b38b0bc3099f172ab8327

Steps to reproduce:
1. Run `:Magit` while running vim with no arguments from a git working directory with unstaged changes.
2. Move cursor down to Unstaged changes section on the line with the first unstaged file.
3. Press <kbd>V</kbd> to enter VISUAL LINE mode.
4. Select any number of lines in the Unstaged changes section.
5. Press <kbd>S</kbd>.

Produces error:

```
Error detected while processing function magit#stage_vselect[8]..<SNR>33_mg_create_diff_from_select[3]..<SNR>33_mg_select_hunk_block[1]..<SNR>33_mg_search_block:                         
line    9:                                                                                                                                                                                
E605: Exception not caught: out_of_block                                                                                                                                                  
Press ENTER or type command to continue
```

Also note:
- Using <kbd>L</kbd> to stage by lines while in VISUAL LINE mode isn't vmapped to an action.
- Behavior is also present when attempting to unstage changes from the Staged changes section.

**Comment by jreybert** [comment]
Hi h3xx,

stage multiple files at once by visually selecting them is not supported for the moment. I know this would be a great feature. I am planning to integrate such feature, but I don't know when.

Anyway, maybe the documentation is not clear enough about this limitation. [Here](https://github.com/jreybert/vimagit#local-mappings) you can see that:

> - If some lines in the hunk are selected (using v), stage only visual selected lines (only works for staging).
> - If some lines in the hunk are marked (using M), stage only marked lines (only works for staging).

For your other points:

> - Using L to stage by lines while in VISUAL LINE mode isn't vmapped to an action.

I am not comfortable with such mapping. The semantic of L is to stage one single line. What vimagit should do if you select multiple lines and press L?

> - Behavior is also present when attempting to unstage changes from the Staged changes section.

This is a current limitation of vimagit, also stated in documentation.

I split your issue in multiple issues.

Thanks for your report!

**Comment by jreybert** [comment]
Splitted issue into:
- #32
- #33

**Comment by h3xx** [comment]
Don't you think that if the feature simply isn't implemented, it shouldn't cause the code to break and throw an exception?

I'm not expecting this feature to be created, I'm just reporting that I was able to **very easily** cause the plugin to [scream and die](http://www.catb.org/jargon/html/S/scream-and-die.html) simply by doing what seemed to me (as a long-time vim-fugitive user) to be normal intuitive usage.

**Comment by jreybert** [comment]
You were right, I missed your point. 

Thanks
