### ISSUE TITLE
feature: allow unstage by visual selection

### ISSUE THREAD

**Issue by jreybert** [jreybert/vimagit#32]

**Comment by slackhead** [comment]
+1 for this

It would certainly make it a lot faster to work with.

**Comment by jreybert** [comment]
Faster? Do you **un**stage a lot? I just would like to be sure you are not misunderstanding this issue.

**Comment by slackhead** [comment]
Er no, I meant to stage by selection. Or does it do that already?

**Comment by jreybert** [comment]
That's what I thought :) And yes, it is already possible! Visual select some lines, and press **S**. See the doc or the readme for other possibilities like **L** or **M**.
