### ISSUE TITLE
hide stash diffs by default

### ISSUE THREAD

**Issue by haifengkao** [jreybert/vimagit#37]
vimagit will show all the diffs in stashes without any folding.
It makes the `magic-playground` unnecessarily cluttered

**Comment by jreybert** [comment]
You are right, something in release 1.4 broke the stash folding.

I included the stashes because it was easy, but it is not very useful for the moment as it is read only.

I'll soon disable stash display by default.

**Comment by haifengkao** [comment]
thanks
