### ISSUE TITLE
pressing 'enter' on a deleted filename will hang vim

### ISSUE THREAD

**Issue by haifengkao** [jreybert/vimagit#38]
If I press 'enter' on a deleted filename, the vim will become unresponsive

**Comment by jreybert** [comment]
In a terminal, could you give me the output of this command please:

> git diff -- your_deleted_filename | wc

**Comment by haifengkao** [comment]
```
git diff -- HFTAGManager.m|wc                                                                                                                                    
       0       0       0

```

**Comment by jreybert** [comment]
halfengkao, I believe that you did  the git diff when your file was staged, right?

Could you please perform the git diff when the deletion of your file is not staged?

Furethermore, could you please give me your vim and git versions?

**Comment by haifengkao** [comment]
Yes, the file is staged.
vim version: 7.4
git version: 2.5.3
If I unstage the file, it will be 

```
git diff -- HFTAGManager.m|wc  
     125     399    4168
```

It turns out that I am a little impatient. 
After I pressed enter,  Vim will be unresponsive for about 10 seconds. 
After 10 seconds, the diff result will be displayed correctly.

**Comment by jreybert** [comment]
It is weird that vim behave so slowly for such display. It is only 125 lines to display.

Is vimagit as slow when displaying such amount of diff, but for a modified or a new file diffs?

**Comment by haifengkao** [comment]
Yes. Actually the amount of time is the same.
It has nothing to do with the amount of diff.
The response time for 305 lines and 6 lines of diff are exactly the same.

But it has something to do with the size of repository.
The larger the repository, the longer it takes to display.

**Comment by jreybert** [comment]
Hi,

could you please get the branch 'next', and send me a profiling report please?
- start vim
- :call magit#utils#start_profile("/tmp/vimagit.log")
- :call magit#show_magit('v')
- press enter on your deleted file
- exit vim

Moreover, do you experience this vimagit freeze only when showing the deleted file, or is it for any operation in vaimgit buffer? And from a terminal, could you give me the result of:

> time git diff -- HFTAGManager.m

Thanks

**Comment by jreybert** [comment]
Hi,

do you encounter the issue? If not, could you please close the issue?

Thanks

**Comment by haifengkao** [comment]
It is gone. Thanks
