### ISSUE TITLE
'q' or ':bw' does not work after ':only'

### ISSUE THREAD

**Issue by goweol** [jreybert/vimagit#41]
I want to see the magit buffer only after I do ':Magit'.

<blockquote>
$ LANG= gvim test.c<br>
:Magit<br>
:only<br>
q<br>
</blockquote>

There occurs 'E444: Cannot close last window'.
If I run ':bw', there occurs "E94: No matching buffer for :call magit#commit_command('CC')".

<blockquote>
:ls<br>
  1 #h   "test.c"                       line 0<br>
  2 %a   "magit-playground"             line 1<br>
:bw 2<br>
</blockquote>

The ':bw 2' command works.

**Comment by goweol** [comment]
Now, I get error below.

<blockquote>
Error detected while processing function magit#close_magit:<br>
line    5:<br>
E499: Empty file name for '%' or '#', only works with ":p:h": ^I^I^Iedit #<br>
</blockquote>

Test sequence is.

<blockquote>
$ LANG= gvim<br>
:Magit<br>
:only<br>
q
</blockquote>

Vimagit version is:
$ git describe --long --dirty --tags
1.4.1-16-gc6a2044

**Comment by jreybert** [comment]
If your problem is not fixed, feel free to reopen the issue.

**Comment by goweol** [comment]
I noticed 'q' problem while I test the dev/multiple_repo branch.
And confirmed this problem exists in next branch.

<blockquote>
$ cd ~/.vim/bundle/vimagit<br>
$ gvim README.md<br>
:Magit<br>
:only<br>
q<br>
:e ../../vimrc<br>
:Magit<br>
:only<br>
q
</blockquote>

Now, vim quits though there are 'README.md' and 'vimrc' buffers.

**Comment by jreybert** [comment]
Does it work well in next branch?

**Comment by jreybert** [comment]
I can't reproduce your issue.

Is vimrc in a git repository?

**Comment by jreybert** [comment]
OK, I can reproduce if 2nd opened file is not in a git repository

**Comment by jreybert** [comment]
magit#show_magit() function should be safer now.

**Comment by goweol** [comment]
The 2nd opend file was in GIT repo.  But I even didn't need to open 2nd file.  Just call the ':Magit|:only|q' twice reproduced the problem.
VIM quits with sequence below.

<pre>
gvim README.me
\M&lt;C-W&gt;oq\M&lt;C-W&gt;oq
</pre>

Now, I cannot reproduce this problem on the dev/multiple_repo (8f8bea6d).
I can reproduce this problem on next (4237501b).
I hope it merged to 'next' soon.

Thanks.

**Comment by jreybert** [comment]
I am waiting some other feedbacks about the multi git repository before merging it to next.

Glad it works.
