### ISSUE TITLE
Pressing 'q' does not close magit, but switches buffer instead.

### ISSUE THREAD

**Issue by slackhead** [jreybert/vimagit#43]
I've noticed that post 1.4 when I press 'q' in the playground it does not close the buffer, it simply switches to the file buffer, leaving playground open.

If I switch to the playground buffer and press 'q' then it will then close it and the file.

**Comment by jreybert** [comment]
There has been some recent changes around this.

Could you try the very last master branch and confirm that the problem persists?

**Comment by slackhead** [comment]
Yes, I've tried with 1.4.2 today 14th Nov and then compared with 14.1. I also recloned the repo to see if I'd done something wrong.

**Comment by jreybert** [comment]
Are you on master or on tag 1.4.2?

Do you have the commit 795e280 ?

If your are up to date with 795e280 , could you describe more precisely your problem, including for example:
- the output of :buffers before you open magit-playground, during it is opened, once it is closed
- how do you open the magit playground
- what is your vesion of vim

could you also provide a step by step command to reproduce the problem.

Thanks

**Comment by slackhead** [comment]
If I checkout  795e280 the results are the same as with master. Tag is 1.4.2.

These are the steps:

I start vim
:buffers shows '1 %a   "[No Name]"                    line 1'
I use leader m or type :Magit
I press 'q'
:buffers shows:
  1 #a   "[No Name]"                    line 1
  2 %a   "magit-playground"             line 1
:bnext
I press 'q'
Playground closes
Vim exits _if_ there are no unsaved files

Vim was built from git on 15/10/2015 (or 10/15 for USA)

**Comment by jreybert** [comment]
There's something I don't understand

> I start vim
> :buffers shows '1 %a "[No Name]" line 1'
> I use leader m or type :Magit

could you give the :buffers output here?

> I press 'q'
> :buffers shows:
> 1 #a "[No Name]" line 1
> 2 %a "magit-playground" line 1

Right now, the active buffer IS magit-playground. Are you sure? It means that magit#close_magit() did not work.

> :bnext

Now, I am totally lost. You were in magit-playground. With :bnext, you should now be in [No name]. If it is the case, 'q' should not be active here. Could you give me the output of :buffers again here?

> I press 'q'
> Playground closes
> Vim exits if there are no unsaved files

And, could you source and execute such function from an empty vim and attach /tmp/log

```
function! Tests()
    redir! > /tmp/log
    echo "1"
    buffers
    echo "2"
    Magit
    buffers
    echo "3"
    call magit#close_magit()
    buffers
    redir END
endfunction
```

**Comment by slackhead** [comment]
I don't know how to quote here, but:

"Right now, the active buffer IS magit-playground. Are you sure? It means that magit#close_magit() did not work."

That's what I'm saying - it doesn't close, it just switches vim to display the next buffer.

vim
buffers
  1 %a   "[No Name]"                    line 1
Magit
buffers
  1 #a   "[No Name]"                    line 1
  2 %a   "magit-playground"             line 1
q
buffers
  1 %a   "[No Name]"                    line 1
  2  h   "magit-playground"             line 0
bnext
buffers
  1 #h   "[No Name]"                    line 1
  2 %a   "magit-playground"             line 1

[log.txt](https://github.com/jreybert/vimagit/files/34638/log.txt)

**Comment by jreybert** [comment]
Indeed, quit the magit buffer means hiding it. If I read the log correctly, press q hide the playground. 

So, what do you expect with q?

**Comment by slackhead** [comment]
In 1.4 it would close it and it wouldn't show in buffer list or airline buffer bar.

**Comment by slackhead** [comment]
Hmm not sure why, but I just switched to 1.4 and then back to 1.4.2 and it is closing it again.

My git prompt shows that I'm on :19de192

**Comment by slackhead** [comment]
In function! magit#close_magit() how about using bdelete instead of close?

function! magit#close_magit()
    try
        bdelete
    catch /^Vim\%((\a+))\=:E444/
        try
            edit #
        catch /^Vim\%((\a+))\=:E\%(194|499)/
            quit
        endtry
    endtry
endfunction

**Comment by slackhead** [comment]
Perhaps some screenshots will help to see what I mean:

I have 3 files open: a, b and c:
http://www.r0t.uk/sshots/shot-9182810054.png

:Magit
http://www.r0t.uk/sshots/shot-2609973000.png

After pressing 'q':
http://www.r0t.uk/sshots/shot-0297197584.png

:ls
http://www.r0t.uk/sshots/shot-1032706793.png

As you can see it is still visible in the airline buffer bar.

**Comment by jreybert** [comment]
Hi slackhead,

I did not forgot you! Thanks for the screenshots.

I am working on a solution, but there is some corner cases I want to fix before pushing it. I hope to push it in the next days.

**Comment by jreybert** [comment]
I believe it is fixed in branch next.

**Comment by slackhead** [comment]
Thanks.
