### ISSUE TITLE
Demo video for readme

### ISSUE THREAD

**Issue by mhartington** [jreybert/vimagit#47]
Hey there, so love the plugin so far.

I recorded a demo of the plugin with a voice over. 

Feel free to use it how ever you want. 

Cheers! 
https://youtu.be/_3wMmmVi6bU

**Comment by jreybert** [comment]
Thanks for your video, you did a great job to present vimagit!

I'll add it to the readme soon.

**Comment by jreybert** [comment]
BTW, in your video, you seems confused with the inline help in magit buffer. This is only plain text, remembering all vimagit comands. You can easily permanently hide it by setting in your vimrc:

> let g:magit_show_help=0

Anyway, it seems that you are the only one to be confused with this. I am planning to make the default behavior to hide inline help in next release (see #46). What do you think? Is this help had helped you a bit, or not at all?

**Comment by mhartington** [comment]
Well, I knew what it was, but just wanted to come at the video as if it was a new users who didn't know anything.

Personally I'd be okay with the inline help commands hidden. Maybe hide all the command except for the `h` command to toggle the help?

**Comment by jreybert** [comment]
Yes, that would be a good compromise.

Thanks for your feedback.
