### ISSUE TITLE
Make Magit window more modal

### ISSUE THREAD

**Issue by mhartington** [jreybert/vimagit#51]
Currently Magit opens as a new buffer next to any active windows.

It would be great if there was an option to open Magit as a modal window replacing the current buffer. 
Similar to how you can set up unite.vim

![](http://www.codeography.com/images/unite-modal-c.gif)

**Comment by jreybert** [comment]
I am not sure to understand the modal thing. 

Try `MagitOnly` and let me know if it is what you want.

**Comment by mhartington** [comment]
Yes! That's what I mean. Sorry, was kind of hard to describe. Next time I'll be sure to RTM. 

Mike Hartington

**Comment by jreybert** [comment]
It's good to see that some stuff I add to vimagit is actually useful for someone 😁
