### ISSUE TITLE
DDD to discard a change throws an error

### ISSUE THREAD

**Issue by mhartington** [jreybert/vimagit#58]
Trying to discard any changes throws an error in nevoid

![screen shot 2016-01-05 at 2 08 16 pm](https://cloud.githubusercontent.com/assets/2835826/12124901/20d9a064-b3b6-11e5-9261-f3355230cf52.png)

**Comment by jreybert** [comment]
Hi,

this error also appears with vim? Could you please dump the output of 'git status'?

**Comment by jreybert** [comment]
@mhartington any update about this bug?

**Comment by mhartington** [comment]
Hey sorry for the delay. Seems that this happens with any untracked files not already in git. Which makes sense

**Comment by jreybert** [comment]
Yes, it makes sense. I wanted to delete the disacarded file in the case this file is not handled by git (it can be scary, but you do not loose more information than discarding changes in a versioned file).

Definietly, this is a bug. I will prompt an understandable message, and maybe add an option to delete the file.
