### ISSUE TITLE
Few suggestions.

### ISSUE THREAD

**Issue by mechanicles** [jreybert/vimagit#6]
The plugin looks good. I don't know about `magit` plugin but I heard it from my emacs friends. As a new user of this plugin, I feel something needs to be improved.

1 - Magit buffer is too much verbose with help info. Try to make it clean. (Not sure how emacs' buffer is..)
2 - It would be great if you mention current branch name in Magit buffer. 

Also please mention `:Magit` command in README.md file

**Comment by jreybert** [comment]
mechanicies, thanks for your time and your suggestions.
1. About verbosity, there is a message on the top of buffer

> To disable this help by default, add "let g:magit_show_help=0" to .vimrc

Maybe I should highlight it.
1. Good idea! It is simple to add. Anyway, there's a lot of awesome things to do around branches.
2. There was a time when it was in README and vimhelp. I put it again.

Thanks again to help me to make something suitable for the most of users.
