### ISSUE TITLE
False positive binary file

### ISSUE THREAD

**Issue by jebaum** [jreybert/vimagit#61]
First of all, awesome plugin! It's already making my life way more pleasant.

When I made a small change to my zshrc (viewable here: https://gist.github.com/anonymous/59dde6c409a776f8d18e), vimagit detected it as a binary file and didn't show a diff. This is due to the characters in quotes on lines 144 and 151. These characters aren't viewable in a web browser as far as I know, but you can see them if you download the raw file from the gist and open it in vim.

Removing those characters from the file causes the diff to show up in vimagit.

**Comment by jreybert** [comment]
Hi jebaum,

thanks for your enthusiasm about vimagit!

I already encountered this false positive, on a vim config file :)

As vim does not embed function do detect binary file, I must use `file` Unix command. If `file` returns a wrong result, I don't know how to perform a better guess than him.

This is indubitably a bug, but for now I don't see how to resolve it.

**Comment by jebaum** [comment]
I didn't realize `file` was identifying it as binary. Interesting. A potential workaround could be checking the output of `git diff` for a file and seeing if it has a textual diff or if git says it's a binary one. Not sure how much work that would be, or how much it might hurt performance. If you don't think that's a good solution, I'll look into this to see if there are more robust ways to detect binary vs text.

**Comment by jreybert** [comment]
I though about using git for this job. I was just worrying about different languages, but it should be possible to force language (it should also work for OSX and windows). Actually, use git could also fix #60 !

I'll take a look for it soon. If you want to contribute, help yourself :)

**Comment by jreybert** [comment]
#60

**Comment by jreybert** [comment]
Hi @jebaum , could you please try the dev/git_diff branch and confirm that it fixes your problem?
