### ISSUE TITLE
Bug in default folding behavior

### ISSUE THREAD

**Issue by jebaum** [jreybert/vimagit#62]
Without setting `g:magit_default_fold_level`, or setting it to 1, when I first load `:Magit`, the hunks are unfolded. I figured out this is because my vimrc has `set foldnestmax=1` in it, which I like for normal editing, but having a higher foldnestmax (like the vim default of 20) is needed for magit. I think the Magit buffer ought to do `setlocal foldnestmax=20` to solve this.

**Comment by jreybert** [comment]
Hi,

it seems to be the proper way to do that. Would you mind to add it in vimagit and propose a pull request? It should be in `magit#show_magit` function, near other `setlocal`assignments.

**Comment by jebaum** [comment]
I'll do that, thanks for pointing me to the right place

**Comment by jreybert** [comment]
Nice! May I ask you to push again, adding "(fix #62)" at the end of the title commit message

**Comment by jebaum** [comment]
done
