### ISSUE TITLE
Refine undo behavior

### ISSUE THREAD

**Issue by jebaum** [jreybert/vimagit#64]
Pressing `u` does a couple of things that I don't think are ideal:

1) immediately after running `Magit`, it will clear the whole buffer
2) toggling display of "help" can be undone with `u`

If `undo` within the context of the Magit buffer would only undo Magit actions (and same with redo of course) it would improve usability. The above two cases are the only two I've noticed where I hit `u` and something I don't want to happen happens, but there may be a couple others I haven't bumped into yet.

The only way I can think of to achieve this would be a little bit hacky with `wundo`, `rundo`, and the code snippet in `:h clear-undo`. I'll try to see if there are better options, or if this could be made optional for people who don't have `undofile` on. It's possible it may not be worth it at all, in which case I may want to explore adding a feature to vim/neovim to enable fine grained control of the undo history.

**Comment by jreybert** [comment]
Hi,

there is a first and clean fix about your issue. Actually, you are right, letting the undo thing like this may let the user think that when it presses `u`, its last magit command is undone (which is not the case!).

This patch (that you can try with the branch `dev/undo`) clears the undo history at each magit buffer update. Then, pressing `u` won't undo the magit changes. But if the user is writing a commit message for example, it can still use `u` to undo what he is typing.

**Comment by jreybert** [comment]
@jebaum did you try this branch? I intend to merge it to next release, let me know your point of view.

**Comment by jebaum** [comment]
I'll start running that branch now and let you know. Glanced at the code, looks pretty good to me. Is it possible to get around that unwanted fold opening with something like `:silent! normal! zc`? with `foldclosed()` and `foldlevel()` it ought to be possible to make sure the folding stays the same even with nesting.

**Comment by jreybert** [comment]
Well, for the fold opening stuff, are you experiencing this? Are do you based your comment on function comment?

The function comment may be unclear, but it says that unwanted unfold may appear if the function is used at the wrong place.
