### ISSUE TITLE
Update gitgutter signs when needed

### ISSUE THREAD

**Issue by jreybert** [jreybert/vimagit#68]

**Comment by fourjay** [comment]
Please consider a user adding a doautocmd custom event (say "MagitWritePost") to address this.
There are a stack of CVS gutter tools. I use quickfixsigns (for a couple of reasons) and there's no reason you should have to support all the variations. With a custom event you:
1) Allow other plugin writers to add integration to your tool.
2) Allow end users to add tasks to this hook themselves
:-)

**Comment by jreybert** [comment]
What a wonderful request! Could you please open another issue please?
