### ISSUE TITLE
Request to add custom UserEvent hook

### ISSUE THREAD

**Issue by fourjay** [jreybert/vimagit#70]
Please consider a user adding a doautocmd custom  User event (say "MagitWritePost") at the end of a commit.
Primary perceived use case, allowing a hook to trigger VCS gutter tools to update, but there are probably other use cases.
Thanks! I've come to enjoy Magit

**Comment by jreybert** [comment]
I think provide the user the buffer being updated as parameter. If you see any other interesting parameters, please add a comment to this issue.

**Comment by jreybert** [comment]
Well, you made me discover doautocmd. That's really interesting and it could have been a clean way to perform such hook.

But it seems to lack a way to provide a parameter, or to target a given file. I would like to provide the user a way to refresh only the updated file.

**Comment by fourjay** [comment]
Can you provide an autoload function that can provide the list of updated files/buffers that can be called in the event handler?

**Comment by jreybert** [comment]
I finally opted for the User event solution. I am not fan passing a parameter through a global function/variable, as the event handler could read out dated data. But as current vimscript seems to be completly sequential, it should be OK.
