### ISSUE TITLE
help message alway show default key map even it's customised 

### ISSUE THREAD

**Issue by butterflyfish** [jreybert/vimagit#72]
at my vimrc, it have 

> g:magit_stage_hunk_mapping = '-'

but vimagit help message still  use 'S'.

**Comment by jreybert** [comment]
Nice one! A pull request is more than welcome.

**Comment by butterflyfish** [comment]
@jreybert , I'm only vim user, and never write vim scripts. Sorry.

**Comment by jreybert** [comment]
That would be a good, start, update message won't be that hard ;)

Anyway, if you really don't want to do this, I'll do.
