### ISSUE TITLE
Add variable for custom git command

### ISSUE THREAD

**Issue by jreybert** [jreybert/vimagit#74]
Ref #39

**Comment by tiagoboldt** [comment]
Fixed for me (OS X, fish shell, latest git from homebrew)

**Comment by jreybert** [comment]
Thanks for your answer less than 5 minutes after the push :)

**Comment by dfishburn** [comment]
Standard Windows cmd.exe.  I am sure some users use Powershell on Windows, but I haven't tried it yet.

**Comment by jreybert** [comment]
@dfishburn does it work for you when you set `g:magit_git_cmd variable` in your vimrc to your git command?

**Comment by dfishburn** [comment]
With the code I sent you which I am running against 1.5.2 (made the same manual change).
Yes, it is the only way I can use Magit.
This 1.6.0 milestone (don't quite understand what a milestone is compared to a branch) but there doesn't appear to be anyway I can test a pre-release ...

**Comment by jreybert** [comment]
@dfishburn , did you try the branch `next`? There is no pre-release, to try next feature you must be on `next` branch.

```
git fetch origin
git checkout origin/next
```

A milestone is like a tag for github.

You can see it like a release, a version number. Branches `master` and `next` continuously move. A milestone/tag/version/WhateverYouCallIt will stay like a... a milestone ;)

**Comment by jreybert** [comment]
@kdurant @dfishburn could you confirm that branch next works well for you? FYI, I removed all environement variable.

To fulfill my understanding, do you use a standard `git` command, or another one? (see #75)

Thanks for your contribution, I would like to make it clear before next release.
