### ISSUE TITLE
Different git command according to environment ( platform/OS/shell) ...

### ISSUE THREAD

**Issue by jreybert** [jreybert/vimagit#75]
At least, following environment have been identified:
- Linux + shell
- FISH shell (Linux, Windows?)
- Windows (which shell?)

Ref #39

**Comment by tiagoboldt** [comment]
➜  ~ which git # Homebrew
/usr/local/bin/git
➜  ~ fish --version
fish, version 2.2.0
➜  ~ sw_vers -productVersion # OS X Version
10.11.3

**Comment by jreybert** [comment]
thanks @tiagoboldt 

I am thinking removing all the NULL config stuff in front of git. I suspect that vimagit will behave well, even with exotic git configuration. I'll see, but in this case this ticket will be rejected.

**Comment by jreybert** [comment]
Finnaly, did not see actual use case.
