### ISSUE TITLE
Go straight into insert mode when committing

### ISSUE THREAD

**Issue by fpnick** [jreybert/vimagit#77]
Hi,

I think it would be more intuitive if vim would jump straight into insert mode after pressing CC to commit, wouldn't it?

Cheers,
Fabian.

**Comment by slackhead** [comment]
+1 for this. I've been thinking the same thing for a while now.

**Comment by jreybert** [comment]
I believe that branch next fix this ticket. Checkout branch next and add this line into your vimrc:

```
autocmd User VimagitEnterCommit startinsert
```

and let me know if it works for you.

**Comment by fpnick** [comment]
Works for me!

**Comment by slackhead** [comment]
Yep.
