### ISSUE TITLE
Unhandled error when commiting an empty stage

### ISSUE THREAD

**Issue by aerosol** [jreybert/vimagit#79]
Steps to reproduce:
1. no staged changes
2. leader M
3. CC
4. type commit message
5. CC

results with

```
Error detected while processing function magit#commit_command[12]..<SNR>71_mg_git_commit:
```

Would be way nicer to warn the user that there's nothing to commit (or simply disable CC).

PS. Thanks for a really nice plugin!

**Comment by jreybert** [comment]
@aerosol thanks for report, I'll give it a look ASAP.

**Comment by jreybert** [comment]
A fix has been pushed on branch next. Could you give it a try before I merge it to master?

Thanks!

**Comment by aerosol** [comment]
@jreybert very cool, works nicely
