### ISSUE TITLE
Error when escaping insert mode in commit section

### ISSUE THREAD

**Issue by aerosol** [jreybert/vimagit#80]
Steps to reproduce:
1. Stage data
2. `CC`
3. `ESC`
4. press `h`

One would expect to move the cursor  one character back, instead an error is produced:

```
Error detected while processing function magit#toggle_help[2]..magit#update_buffer[9]..<SNR>71_mg_get_commit_msg[21]..magit#utils#
strip_array:
line    2:
E684: list index out of range: 0
E15: Invalid expression: ( a:array[start] == '' )
Press ENTER or type command to continue
```

**Comment by jreybert** [comment]
Hi @aerosol ,

thanks for your feedback. According to #81, this is definitely a misconception of key mapping.

I'll update it soon.

PS: thanks for your tweet :)

**Comment by aerosol** [comment]
@jreybert hey don't mention it, thanks for the plugin! :)

**Comment by jreybert** [comment]
A fix has been pushed on branch next. Could you give it a try before I merge it to master?

Thanks!

**Comment by aerosol** [comment]
@jreybert `next` branch I assume?

**Comment by aerosol** [comment]
@jreybert works for me! :heart: 

The message `Press h to display help` should be changed accordingly. Thank you!

**Comment by jreybert** [comment]
Nice catch, thanks
