### ISSUE TITLE
edit commit

### ISSUE THREAD

**Issue by dtb11288** [jreybert/vimagit#81]
Hi jreybert,

Please change help command from "h" to "?", when I want to edit wrong position, press "h" should go to left. except this issue always annoy me, everything else work great.

Thanks for amazing plugin

**Comment by aerosol** [comment]
@dtb11288 duplicate, reported that yesterday https://github.com/jreybert/vimagit/issues/80

**Comment by jreybert** [comment]
@dtb11288 exact same bug discovered by two persons in 1 day O.o

Thanks for you report.

I close this ticket as it duplicates #80

**Comment by jreybert** [comment]
A fix has been pushed on branch next. Could you give it a try before I merge it to master?

Thanks!
