### ISSUE TITLE
Add <nowait> to magit mappings

### ISSUE THREAD

**Issue by ghost** [jreybert/vimagit#85]
Hey, consider adding <nowait> to g:magit_close_mapping to reduce delay for those who have global q\* mappings set.

**Comment by jreybert** [comment]
Ho, I did not know this option...

Well, I will be consider it, but maybe not only for q mapping. I'll check how other plugins play with this in special buffers mapping.

**Comment by alok** [comment]
I'm also interested in this.

I use the `s` key to stage, but I have a global mapping that conflicts, and it's annoying to have to wait a second for the mapping to work.

**Comment by jreybert** [comment]
I understand your concern.

I am quite reluctant to add `nowait`, I don't understand all the possible consequences for the moment.

I would like to do a full review of technical ways to provide default mapping first, and see the best fit for vimagit, for example using `<Plug>` prefix. I do believe it should fix your concern.

See http://whileimautomaton.net/2008/09/27022735

**Comment by jreybert** [comment]
@Shougo 's code to use `nowait`

```
function! s:nowait_map(mode) abort "{{{
  return a:mode.'map <buffer>'
        \ . ((v:version > 703 || (v:version == 703 && has('patch1261'))) ?
        \ '<nowait>' : '')
endfunction "}}}
```

**Comment by jreybert** [comment]
@kwinczek @Alok could you please give a try to branch `dev/mapping`

**Comment by ghost** [comment]
@jreybert Seems alright to me. Thanks!
