### ISSUE TITLE
Feature: check user's commit message length

### ISSUE THREAD

**Issue by scps950707** [jreybert/vimagit#86]
![_003](https://cloud.githubusercontent.com/assets/6916149/15453040/813a9b14-2037-11e6-9184-e62a90c1904c.png)
vim changes the color of commit message text color to tell us not to write commit message longer than 50 characters in first line.
But magit doesn't
![magit ---home-scps950707-github-gittest - vim_004](https://cloud.githubusercontent.com/assets/6916149/15453043/d4d695ac-2037-11e6-81fb-a5ecaf12d407.png)
I hope vimagit can implement same feature as vim, thanks!

**Comment by scps950707** [comment]
I resolve this problem by intergrating this plugin:[vim-lengthmatters](https://github.com/scps950707/vim-lengthmatters)  with vimagit
Then I Add 

```
autocmd User VimagitEnterCommit let g:lengthmatters_magit_mode=1|:LengthmattersReload
```

to my vimrc and works
![_006](https://cloud.githubusercontent.com/assets/6916149/16532760/99ddad98-4006-11e6-8e1f-0af948f701bf.jpg)

**Comment by jreybert** [comment]
Great, thanks for the tip!

**Comment by scps950707** [comment]
I also have another solution by just Modify vimagit's syntax rule to do the same feaure
[this commit](https://github.com/scps950707/vimagit/commit/4736fd7c56d9cf4a1ed0a3bde54ec68babcfb621)
And now works like this
![_002](https://cloud.githubusercontent.com/assets/6916149/16579992/032e6f96-42d5-11e6-8cca-850a6e6162f2.jpg)

**Comment by jreybert** [comment]
Nice trick. But there are solutions to detect the first non blank line in a commit message, without adding a string in front of the line. A PR with such solution would be welcomed.

**Comment by scps950707** [comment]
Hmm..I think it's a little bit diffcult, I can't figure out this regex mattern to match first non blank line in a commit message

**Comment by jreybert** [comment]
Indeed, the pattern is the following: the first non blank line after the pattern "Commit message\n==============\n"

**Comment by Bob131** [comment]
Since this isn't supported in vimagit itself, can this issue be reopened?

**Comment by scps950707** [comment]
OK ,I reopen it.

**Comment by jreybert** [comment]
:+1: thanks @scps950707 for the PR! It has been merged in `next` and will be soon merged in `master`
