### ISSUE TITLE
Add remap setting for jumping to next/previous hunk

### ISSUE THREAD

**Issue by wikimatze** [jreybert/vimagit#87]
I like to use `C-n` and `C-p` from https://github.com/junegunn/fzf.vim to jump to next/previous hunk. The documentation adds mapping for all other commands, except those ones. See line https://github.com/jreybert/vimagit/blob/master/doc/vimagit.txt#L230.

Maybe it's just missing in the documentation?

**Comment by jreybert** [comment]
5 months for this issue... sorry.

Yes, it's just missing in the doc (updated). Variables are:
`g:magit_jump_next_hunk`
`g:magit_jump_prev_hunk`

**Comment by wikimatze** [comment]
Thanks you so much.

```
let g:magit_jump_next_hunk = '<C-n>'
let g:magit_jump_prev_hunk = '<C-p>'
```

works as intended.

**Comment by jreybert** [comment]
:+1:
