### ISSUE TITLE
Error when vim files are in a path with spaces

### ISSUE THREAD

**Issue by wezm** [jreybert/vimagit#89]
I store my vim files in Dropbox. The path has spaces and brackets in it (Note that the `Dropbox (Personal)` bit wasn't my choice. When you add a Dropbox for business account they rename the Dropbox folder to this and add a `Dropbox (Business)` one). Whilst everything else works with this arrangement, vimagit does not:

```
Error detected while processing /Users/wmoore/Dropbox (Personal)/Dot Files/vim/plugged/vimagit/plugin/magit.vim:
line   18:
E172: Only one file name allowed: source /Users/wmoore/Dropbox (Personal)/Dot Files/vim/plugged/vimagit/plugin/../common/magit_common.vim
```

**Comment by jreybert** [comment]
Gasp, I think the test suite tests that staged file with space are well handled, but I don't think I test repository path with white spaces...

I'll give it a look, thanks.

**Comment by wezm** [comment]
Note this isn't about the repository path having spaces it's vim's configuration files being in a location with spaces in it. In this case Vimagit errors out when opening vim.

**Comment by jreybert** [comment]
I misread it. Thanks for the tip.

**Comment by jreybert** [comment]
Arh, it's been such a pain to reproduce your setup! Spaces should be forbidden, everywhere! :)

Could you try the branch next, and let me know if it fixes your problem?

Thanks for the issue.

**Comment by wezm** [comment]
Yeah it was a terrible choice by Dropbox to not only include spaces but brackets as well. I'll give it a try when I have a moment. Might not be until the weekend.

**Comment by jreybert** [comment]
No problem, you waited 3 months, I can wait too :)

**Comment by jreybert** [comment]
Could you confirm it has fixed your problem before I merge it into master.

**Comment by wezm** [comment]
It gets further (vim loads without error) but doesn't look like it's entirely fixed:

```
Error detected while processing function magit#show_magit[11]..magit#git#is_work_tree[11]..magit#utils#lcd:
line    1:
E172: Only one file name allowed: cd /Users/wmoore/Dropbox (Personal)/Dot Files
Error detected while processing function magit#show_magit:
line   11:
E170: Missing :endfor
Press ENTER or type command to continue
```

This happened when running `:Magit` when `:pwd` is `/Users/wmoore/Dropbox (Personal)/Dot Files`, which is a git repo.

**Comment by jreybert** [comment]
I believe this is now fixed in banch next.

All tests in integration are done with the tested repository path containing spaces.

Last flow in integration is that vimagit path does not contain space.

Thanks for your feedback!

**Comment by wezm** [comment]
Yep working now 👍 Thanks.
