### ISSUE TITLE
Handling signing of commit messages

### ISSUE THREAD

**Issue by mhartington** [jreybert/vimagit#90]
Recently github has allowed people to sign their commits for verification purpose

https://help.github.com/articles/signing-commits-using-gpg/

Currently, if I try to use vimagit with gpg signing enabled, you get this.

<img width="1680" alt="screen shot 2016-08-13 at 3 22 39 pm" src="https://cloud.githubusercontent.com/assets/2835826/17645143/9e7fb532-616a-11e6-843d-b8a6b7f74042.png">

And vim freezes and cannot be recovered. 
Not suer what the best way to handle this, but thought I'd bring it to your attention.

**Comment by jreybert** [comment]
Thanks Mike to bring my attention to this feature.

I need to work again on visit, very soon.

**Comment by wikimatze** [comment]
Have the same issue, but a `C-f` and `<C-b` solves this issue for me.

**Comment by jreybert** [comment]
When I try with my vim configuration (I use a terminal nvim with X support), I get a popup asking me for my key.

What is your vim configuration?

If you confirm it happens with a vim without X support, I will disable commit signin when done from vimagit with a vim without X support, with a warning. If you're comfortable with such things as gpg-agent, I may add a check 'if gpg-agent enabled and ready", but I will need your support with this.

**Comment by mhartington** [comment]
Hey sorry, for the silence on this end...

I do not get a popup, but rather this.
![screen shot 2016-12-20 at 4 15 37 pm](https://cloud.githubusercontent.com/assets/2835826/21368215/9c25c888-c6cf-11e6-8524-98db0f7c5940.png)

Where I'm unable to to enter any text.

My dot files are here

https://github.com/mhartington/dotfiles/blob/master/config/nvim/init.vim

I'm using macOS, iterm2, nvim, and tmux.

**Comment by mhartington** [comment]
Update: Looks like this is because nvim does not behave the same as vim. Went back and setup an gpg-agent and a native window showed up. Closing as this is something that would require nvim specific code to work around, and an agent is just as good.
