### ISSUE TITLE
After remapping, CC adds previous commit message

### ISSUE THREAD

**Issue by hkupty** [jreybert/vimagit#94]
After setting `let g:magit_commit_mapping="cc"`, if I do multiple commits for the same repo or without closing vim (changing pwd to another project) it places the previous commit message.

It keeps the commit mode as `normal`, though.

**Comment by jreybert** [comment]
I can't reproduce your issue. Could you:
- try to reproduce disabling all the others plugins
- make a step by step description

Thanks

**Comment by jreybert** [comment]
Hi,

could you please provide a step by step description on how to reproduce your bug? I would like to fix it for next release.

**Comment by hkupty** [comment]
Sorry for taking long to answer, I've been on a rush for the last few days.

I'm thinking this may be related to `tcd` somehow. When I opened the issue, it looked like (for some random order of events) that changing the commit mapping would cause the message to appear, even if normal commit.

I'll ask you to keep this on-hold as I'll investigate further (while addressing the comments for the PRs #93 and #95).

**Comment by jreybert** [comment]
OK thanks for your feedback.

**Comment by jreybert** [comment]
Someone pointed me this out:
when this has happened to you, did you began a commit with another tool such as `git gui` or `git cola`?

**Comment by hkupty** [comment]
No. The thing is, it used to happen prior to fixing tcd. I'm using `next` now and it never happened again (it was pretty common before).

~~I think we can close this for now.~~ I'm using vimagit on daily basis and I'm pretty sure fixing `tcd` fixed it.

Just found out why it happens:
`{,t,l}cd` is on a path, but the file is from other path This causes the vimagit window to open for the repo of the current file, but with the message from previous commit of the repo of `cd/tcd/lcd`.

**Comment by alok** [comment]
FWIW, I've also had this issue. I'm using `next`.

**Comment by jreybert** [comment]
@Alok do you use `tcd`?

**Comment by alok** [comment]
@jreybert No.

**Comment by jreybert** [comment]
Do you use tools like `git gui` or `git cola`?

**Comment by alok** [comment]
No. I only use the command line, and recently I've only used vimagit,
except to push.

**Comment by hkupty** [comment]
@Alok can you reproduce the bug? I'm pretty sure this is fixed on `next`..

**Comment by alok** [comment]
I just updated and I'm not seeing it.
