### ISSUE TITLE
Fix cursor position after staging

### ISSUE THREAD

**Issue by jreybert** [jreybert/vimagit#96]
Cursor should stay at relative same place (not necessarily same line) after staging.

Proposed by @ntcong

**Comment by alok** [comment]
I get the inverse issue: when I *un*stage a change, the cursor jumps to the top.

**Comment by jreybert** [comment]
Could you be more precise?
- do you unstage a hunk or an entire file?
- what is its position in the staged list?

**Comment by alok** [comment]
- Single hunk.
- Didn't check.

It's odd but this issue doesn't consistently appear, so it may be some other issue. I'll keep testing it and let you know.

**Comment by jreybert** [comment]
@ntcong @yevhen-m this is even better now!

**Comment by yevhen-m** [comment]
@jreybert thanks.
